custom:
  enable_rule_generator: false
  overwrite_original_rules: true

  rulesets:
  - {import: https://raw.githubusercontent.com/y01and3/Subconverter-Rules/main/rules.txt}

  proxy_groups:
  - {import: https://raw.githubusercontent.com/y01and3/Subconverter-Rules/main/groups.txt}

  clash_rule_base: https://raw.githubusercontent.com/y01and3/Subconverter-Rules/main/base.tpl
  surge_rule_base: https://raw.githubusercontent.com/y01and3/Subconverter-Rules/main/base.tpl
  surfboard_rule_base: https://raw.githubusercontent.com/y01and3/Subconverter-Rules/main/base.tpl
  mellow_rule_base: https://raw.githubusercontent.com/y01and3/Subconverter-Rules/main/base.tpl
  quan_rule_base: https://raw.githubusercontent.com/y01and3/Subconverter-Rules/main/base.tpl
  quanx_rule_base: https://raw.githubusercontent.com/y01and3/Subconverter-Rules/main/base.tpl

  rename_node:
  - {import: https://raw.githubusercontent.com/y01and3/Subconverter-Rules/main/rename.txt}

  add_emoji: true
  remove_old_emoji: true
#  emojis:
#  - {import: snippets/emoji.txt}

#  include_remarks: []
#  exclude_remarks: []
#  template_args:
#  - {key: clash.dns.port, value: 5353}