version = 1
[custom]
enable_rule_generator = false
overwrite_original_rules = true

# Options for custom base configuration file
clash_rule_base = "https://raw.githubusercontent.com/y01and3/Subconverter-Rules/main/base.tpl"
surge_rule_base = "https://raw.githubusercontent.com/y01and3/Subconverter-Rules/main/base.tpl"
surfboard_rule_base = "https://raw.githubusercontent.com/y01and3/Subconverter-Rules/main/base.tpl"
mellow_rule_base = "https://raw.githubusercontent.com/y01and3/Subconverter-Rules/main/base.tpl"
quan_rule_base = "https://raw.githubusercontent.com/y01and3/Subconverter-Rules/main/base.tpl"
quanx_rule_base = "https://raw.githubusercontent.com/y01and3/Subconverter-Rules/main/base.tpl"

# Options for adding emojis
add_emoji = true
remove_old_emoji = true

# Options for filtering nodes
#include_remarks = []
#exclude_remarks = []

[[rename]]
import = "https://raw.githubusercontent.com/y01and3/Subconverter-Rules/main/rename.toml"

[[custom_groups]]
import = "https://raw.githubusercontent.com/y01and3/Subconverter-Rules/main/groups.toml"

[[rulesets]]
import = "https://raw.githubusercontent.com/y01and3/Subconverter-Rules/main/rules.txt"


#[[template_args]]
#key = "clash.dns.port"
#value = "5353"