version = 1
[custom]
enable_rule_generator = false
overwrite_original_rules = ture

# Options for custom base configuration file
clash_rule_base = ""
surge_rule_base = ""
surfboard_rule_base = ""
mellow_rule_base = ""
quan_rule_base = ""
quanx_rule_base = ""

# Options for adding emojis
add_emoji = true
remove_old_emoji = true

# Options for filtering nodes
#include_remarks = []
#exclude_remarks = []

[[custom_groups]]
import = ""

[[rulesets]]
import = ""

[[rename]]
import = ""


#[[template_args]]
#key = "clash.dns.port"
#value = "5353"