[[rulesets]]
group = "REJECT"
ruleset = "https://raw.githubusercontent.com/AGWA5783/Profiles/master/Surge/Ruleset/Reject.list"
type = "surge-ruleset"

[[rulesets]]
group = "REJECT"
ruleset = "https://raw.githubusercontent.com/AGWA5783/Profiles/master/Surge/Ruleset/Guard/Hijacking.list"
type = "surge-ruleset"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/y01and3/Subconverter-Rules/main/RuleSet/MyForceDirect.list"
type = "surge-ruleset"

[[rulesets]]
group = "Proxies"
ruleset = "https://raw.githubusercontent.com/y01and3/Subconverter-Rules/main/RuleSet/MyForceProxy.list"
type = "surge-ruleset"

[[rulesets]]
group = "Telegram"
ruleset = "https://raw.githubusercontent.com/AGWA5783/Profiles/master/Surge/Ruleset/Extra/Telegram/Telegram.list"
type = "surge-ruleset"

[[rulesets]]
group = "Bahamut"
ruleset = "https://raw.githubusercontent.com/AGWA5783/Profiles/master/Surge/Ruleset/StreamingMedia/Video/Bahamut.list"
type = "surge-ruleset"

[[rulesets]]
group = "Bilibili"
ruleset = "https://raw.githubusercontent.com/y01and3/Subconverter-Rules/main/RuleSet/Bilibili.list"
type = "surge-ruleset"

[[rulesets]]
group = "YouTube"
ruleset = "https://raw.githubusercontent.com/AGWA5783/Profiles/master/Surge/Ruleset/StreamingMedia/Video/YouTube.list"
type = "surge-ruleset"

[[rulesets]]
group = "OpenAI"
ruleset = "https://raw.githubusercontent.com/AGWA5783/Profiles/master/Surge/Ruleset/Extra/OpenAI/OpenAI.list"
type = "surge-ruleset"

[[rulesets]]
group = "Bing"
ruleset = "https://raw.githubusercontent.com/AGWA5783/Profiles/master/Surge/Ruleset/Extra/Bing/Bing.list"
type = "surge-ruleset"

[[rulesets]]
group = "Bing"
ruleset = "https://raw.githubusercontent.com/AGWA5783/Profiles/master/Surge/Ruleset/Extra/Microsoft/MicrosoftEdge.list"
type = "surge-ruleset"

[[rulesets]]
group = "Google"
ruleset = "https://raw.githubusercontent.com/AGWA5783/Profiles/master/Surge/Ruleset/Extra/Google/Google.list"
type = "surge-ruleset"

[[rulesets]]
group = "OneDrive"
ruleset = "https://raw.githubusercontent.com/AGWA5783/Profiles/master/Surge/Ruleset/Extra/Microsoft/OneDrive.list"
type = "surge-ruleset"

[[rulesets]]
group = "Steam"
ruleset = "https://raw.githubusercontent.com/AGWA5783/Profiles/master/Surge/Ruleset/Extra/Game/Steam.list"
type = "surge-ruleset"

[[rulesets]]
group = "Emby"
ruleset = "https://raw.githubusercontent.com/y01and3/Subconverter-Rules/main/RuleSet/Emby.list"
type = "surge-ruleset"

[[rulesets]]
group = "Proxies"
ruleset = "https://raw.githubusercontent.com/AGWA5783/Profiles/master/Surge/Ruleset/Global.list"
type = "surge-ruleset"

[[rulesets]]
group = "Apple"
ruleset = "https://raw.githubusercontent.com/AGWA5783/Profiles/master/Surge/Ruleset/Extra/Apple/Apple.list"
type = "surge-ruleset"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/AGWA5783/Profiles/master/Surge/Ruleset/China.list"
type = "surge-ruleset"

[[rulesets]]
group = "DIRECT"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "DIRECT"
ruleset = "IP-CIDR,10.0.0.0/8"

[[rulesets]]
group = "DIRECT"
ruleset = "IP-CIDR,172.16.0.0/12"

[[rulesets]]
group = "DIRECT"
ruleset = "IP-CIDR,192.168.0.0/16"

[[rulesets]]
group = "Final"
ruleset = "[]MATCH"